### ISSUE TITLE
Cannot install the package via composer - not found error

### ISSUE THREAD

**Issue by danielnegoita** [ZiNETHQ/spark-roles#3]
I've run
`composer require zinethq/spark-roles`

and I get 

```
  [InvalidArgumentException]
  Could not find package zinethq/spark-roles at any version for your minimum-
  stability (stable). Check the package spelling or your minimum-stability
```

I've tried in homestead and outside, same error. 

I have Spark 4.0.5 installed (with Laravel 5.4)

How can I fix this?

**Comment by drjonnicholson** [comment]
I may have removed the release tag since we had some remedial issues. Try using this in your composer config:

```json
 "zinethq/spark-roles": "dev-master"
```

And add this to your `repositories` block:
```json
       {
            "type": "vcs",
            "url": "git@github.com:ZiNETHQ/spark-roles.git"
        },
```

That should point composer to get the most recent commit from git.

I expect we'll do a proper release in a month or so when we're happy the project we've developed it for has gone live.

**Comment by drjonnicholson** [comment]
Did this solve your problem @danielnegoita?

**Comment by aalihusni** [comment]
Works for me. tq very much

**Comment by drjonnicholson** [comment]
Great stuff!
