### ISSUE TITLE
Still relevant? 

### ISSUE THREAD

**Issue by scottybo** [ZiNETHQ/spark-roles#9]
Does this package extend Sparks current role management or is it a complete replacement?

For reference: https://spark.laravel.com/docs/4.0/teams#team-roles

**Comment by drjonnicholson** [comment]
Hi @scottybo,

Yes. As far as I'm aware Spark hasn't changed its roles mechanism since version 2 (https://spark.laravel.com/docs/2.0/teams#team-roles) when we originally wrote this.

This also adds a whole additional layer of functionality, such as dynamically populating the spark developer array based on a role on a team or a user.
